//! oxiloader — a minimal ASI proxy loader.
//!
//! Built once per proxy name (see the cargo features). At load it forwards its
//! exports to the real System32 DLL, then loads every `*.asi` next to it — that
//! is the whole job. No config, no manifest, no hooks.
//!
//! Design notes:
//! - x64 only (matches modern games).
//! - No embedded SxS manifest: a Common-Controls dependency is exactly what
//!   broke recent Ultimate ASI Loader builds, so we ship none.
//! - The original DLL is resolved synchronously in DllMain so the game's imports
//!   are valid the instant it calls them; the `.asi` plugins (which may run heavy
//!   code in their own DllMain) are loaded on a fresh thread to stay clear of the
//!   loader lock.

#![allow(non_snake_case, dead_code, static_mut_refs)]

use core::ffi::c_void;
use std::os::windows::ffi::{OsStrExt, OsStringExt};

// Generated by build.rs: TARGET_DLL, EXPORT_NAMES, the naked forwarding stubs,
// and store_ptr().
include!(concat!(env!("OUT_DIR"), "/exports_generated.rs"));

type HMODULE = *mut c_void;
type HANDLE = *mut c_void;
type FARPROC = Option<unsafe extern "system" fn() -> isize>;

const DLL_PROCESS_ATTACH: u32 = 1;

extern "system" {
    fn DisableThreadLibraryCalls(module: HMODULE) -> i32;
    fn LoadLibraryExW(name: *const u16, file: HANDLE, flags: u32) -> HMODULE;
    fn LoadLibraryW(name: *const u16) -> HMODULE;
    fn GetProcAddress(module: HMODULE, name: *const u8) -> FARPROC;
    fn GetSystemDirectoryW(buffer: *mut u16, size: u32) -> u32;
    fn GetModuleFileNameW(module: HMODULE, buffer: *mut u16, size: u32) -> u32;
    fn CreateThread(
        attrs: *mut c_void,
        stack: usize,
        start: unsafe extern "system" fn(*mut c_void) -> u32,
        param: *mut c_void,
        flags: u32,
        id: *mut u32,
    ) -> HANDLE;
    fn CloseHandle(handle: HANDLE) -> i32;
}

static mut SELF_MODULE: usize = 0;

/// Load the genuine System32 DLL and point every forwarding stub at it.
unsafe fn resolve_original() {
    let mut dir = [0u16; 260];
    let n = GetSystemDirectoryW(dir.as_mut_ptr(), dir.len() as u32) as usize;
    if n == 0 || n >= dir.len() {
        return;
    }

    let mut path: Vec<u16> = dir[..n].to_vec();
    path.push(b'\\' as u16);
    path.extend(TARGET_DLL.encode_utf16());
    path.push(0);

    // Absolute path: bypasses search order entirely, so we always get the real one.
    let original = LoadLibraryExW(path.as_ptr(), core::ptr::null_mut(), 0);
    if original.is_null() {
        return;
    }

    for (i, name) in EXPORT_NAMES.iter().enumerate() {
        let mut c: Vec<u8> = name.bytes().collect();
        c.push(0);
        if let Some(func) = GetProcAddress(original, c.as_ptr()) {
            store_ptr(i, func as usize);
        }
    }
}

/// Load every `*.asi` in `dir` and call its `InitializeASI` export.
fn load_asi_from(dir: &std::path::Path) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let is_asi = path
            .extension()
            .map(|e| e.eq_ignore_ascii_case("asi"))
            .unwrap_or(false);
        if !is_asi {
            continue;
        }

        let wide: Vec<u16> = path
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect();
        unsafe {
            let module = LoadLibraryW(wide.as_ptr());
            if module.is_null() {
                continue;
            }
            if let Some(func) = GetProcAddress(module, b"InitializeASI\0".as_ptr()) {
                let init: unsafe extern "system" fn() = core::mem::transmute(func);
                init();
            }
        }
    }
}

unsafe extern "system" fn asi_thread(_param: *mut c_void) -> u32 {
    let mut buffer = [0u16; 1024];
    let n = GetModuleFileNameW(SELF_MODULE as HMODULE, buffer.as_mut_ptr(), buffer.len() as u32)
        as usize;
    if n == 0 {
        return 0;
    }

    let self_path = std::path::PathBuf::from(std::ffi::OsString::from_wide(&buffer[..n]));
    let dir = match self_path.parent() {
        Some(d) => d.to_path_buf(),
        None => return 0,
    };

    // Next to the DLL (the game folder), then an optional `plugins` subfolder.
    load_asi_from(&dir);
    load_asi_from(&dir.join("plugins"));
    0
}

#[no_mangle]
pub extern "system" fn DllMain(module: HMODULE, reason: u32, _reserved: *mut c_void) -> i32 {
    if reason == DLL_PROCESS_ATTACH {
        unsafe {
            SELF_MODULE = module as usize;
            DisableThreadLibraryCalls(module);
            resolve_original();
            let thread = CreateThread(
                core::ptr::null_mut(),
                0,
                asi_thread,
                core::ptr::null_mut(),
                0,
                core::ptr::null_mut(),
            );
            if !thread.is_null() {
                CloseHandle(thread);
            }
        }
    }
    1
}
