//! oxiloader — a minimal ASI proxy loader.
//!
//! Built once per proxy name (see the cargo features). At load it forwards its
//! exports to the real System32 DLL, then loads every `*.asi` next to it — that
//! is the whole job. No config, no manifest.
//!
//! Design notes:
//! - x64 only.
//! - No embedded manifest and no runtime dependencies beyond the OS, so the
//!   binary maps cleanly across host processes.
//! - The original DLL is resolved synchronously in `DllMain`, so the host's
//!   imports are valid the instant they are called.
//! - Plugins run arbitrary code in their own `DllMain`, so they are never loaded
//!   under the loader lock. *How* we defer depends on how we were loaded, which
//!   `DllMain`'s `reserved` argument tells us:
//!     * Static import (`reserved != null`) — the host's entry point has not run
//!       yet. We install a one-shot trampoline over the host's entry point and
//!       load plugins from there: on the host's own thread, after the process is
//!       fully initialized, before any host code runs. Deterministic ordering,
//!       no race. This is the path real games take, and the one that newer
//!       Windows 11 loader behavior (25H2 / KB5095093) broke for the old
//!       spawn-a-thread-from-DllMain approach.
//!     * Dynamic load (`reserved == null`, i.e. `LoadLibrary`) — the process is
//!       already past its entry point, so there is nothing to trampoline. We
//!       load plugins from a spawned thread, which is safe here.

#![allow(non_snake_case, dead_code, static_mut_refs)]
// Deliberate FFI patterns: Win32 type names, a generated helper, a nul byte string,
// and DllMain's OS-mandated signature (which cannot be marked `unsafe`).
#![allow(
    clippy::upper_case_acronyms,
    clippy::missing_safety_doc,
    clippy::manual_c_str_literals,
    clippy::not_unsafe_ptr_arg_deref
)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicU32, Ordering};
use std::os::windows::ffi::{OsStrExt, OsStringExt};

// Generated by build.rs: TARGET_DLL, EXPORT_NAMES, the naked forwarding stubs,
// and store_ptr().
include!(concat!(env!("OUT_DIR"), "/exports_generated.rs"));

type HMODULE = *mut c_void;
type HANDLE = *mut c_void;
type FARPROC = Option<unsafe extern "system" fn() -> isize>;

const DLL_PROCESS_ATTACH: u32 = 1;
const PAGE_EXECUTE_READWRITE: u32 = 0x40;

extern "system" {
    fn DisableThreadLibraryCalls(module: HMODULE) -> i32;
    fn LoadLibraryExW(name: *const u16, file: HANDLE, flags: u32) -> HMODULE;
    fn LoadLibraryW(name: *const u16) -> HMODULE;
    fn GetProcAddress(module: HMODULE, name: *const u8) -> FARPROC;
    fn GetSystemDirectoryW(buffer: *mut u16, size: u32) -> u32;
    fn GetModuleHandleW(name: *const u16) -> HMODULE;
    fn GetModuleFileNameW(module: HMODULE, buffer: *mut u16, size: u32) -> u32;
    fn VirtualProtect(addr: *mut c_void, size: usize, new: u32, old: *mut u32) -> i32;
    fn FlushInstructionCache(process: HANDLE, base: *const c_void, size: usize) -> i32;
    fn GetCurrentProcess() -> HANDLE;
    fn CreateThread(
        attrs: *mut c_void,
        stack: usize,
        start: unsafe extern "system" fn(*mut c_void) -> u32,
        param: *mut c_void,
        flags: u32,
        id: *mut u32,
    ) -> HANDLE;
    fn CloseHandle(handle: HANDLE) -> i32;
}

static mut SELF_MODULE: usize = 0;

// Entry-point trampoline state. `REAL_ENTRY` holds the host entry-point address
// and is jumped through by the naked thunk (same idiom as the forwarding stubs).
static mut REAL_ENTRY: usize = 0;
static mut SAVED_ENTRY_BYTES: [u8; JMP_LEN] = [0; JMP_LEN];
// Guards the actual plugin load so it happens exactly once, whichever path fires.
static ASI_LOADED: AtomicU32 = AtomicU32::new(0);

// A 64-bit absolute indirect jump: `jmp qword ptr [rip+0]` (FF 25 00 00 00 00)
// followed by the 8-byte target. Position-independent, clobbers no register.
const JMP_LEN: usize = 14;

/// Load the genuine System32 DLL and point every forwarding stub at it.
unsafe fn resolve_original() {
    let mut dir = [0u16; 260];
    let n = GetSystemDirectoryW(dir.as_mut_ptr(), dir.len() as u32) as usize;
    if n == 0 || n >= dir.len() {
        return;
    }

    let mut path: Vec<u16> = dir[..n].to_vec();
    path.push(b'\\' as u16);
    path.extend(TARGET_DLL.encode_utf16());
    path.push(0);

    // An absolute path bypasses the DLL search order, guaranteeing the genuine system DLL.
    let original = LoadLibraryExW(path.as_ptr(), core::ptr::null_mut(), 0);
    // Bail if the loader handed back our own module (proxy base-name collision):
    // resolving exports against ourselves would point every forwarding stub at
    // itself, an infinite jmp loop on the first forwarded call.
    if original.is_null() || original as usize == SELF_MODULE {
        return;
    }

    // Fill every forwarding pointer from the genuine DLL (by name, and by ordinal
    // for NONAME exports). Generated in build.rs alongside the ordinal-exact table.
    resolve_exports(original);
}

/// Load every `*.asi` in `dir` and call its `InitializeASI` export. `seen` holds
/// the lowercased file names already loaded; a name present in more than one
/// swept directory is loaded only the first time it is encountered.
fn load_asi_from(dir: &std::path::Path, seen: &mut std::collections::HashSet<std::ffi::OsString>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let is_asi = path
            .extension()
            .map(|e| e.eq_ignore_ascii_case("asi"))
            .unwrap_or(false);
        if !is_asi {
            continue;
        }

        // Skip a plugin whose file name we have already loaded from another
        // directory. Windows keys loaded modules by base name, so a second
        // LoadLibraryW would hand back the existing handle and we would just
        // re-run its InitializeASI — a double-init of one module. Compare
        // case-insensitively, matching the file system.
        let name = match path.file_name() {
            Some(n) => n.to_ascii_lowercase(),
            None => continue,
        };
        if !seen.insert(name) {
            continue;
        }

        let wide: Vec<u16> = path
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect();
        unsafe {
            let module = LoadLibraryW(wide.as_ptr());
            if module.is_null() {
                continue;
            }
            if let Some(func) = GetProcAddress(module, b"InitializeASI\0".as_ptr()) {
                let init: unsafe extern "system" fn() = core::mem::transmute(func);
                init();
            }
        }
    }
}

/// Load `*.asi` from this DLL's own directory and its optional `plugins` subfolder.
/// Idempotent: the plugin sweep runs at most once regardless of how it is reached.
fn load_all_asi() {
    if ASI_LOADED.swap(1, Ordering::SeqCst) != 0 {
        return;
    }

    // Our own module path, growing the buffer if the path would truncate (on
    // truncation GetModuleFileNameW returns the buffer length with no room for a
    // null, so `n == buffer.len()` means "try bigger").
    let mut buffer = vec![0u16; 1024];
    let n = loop {
        let n = unsafe {
            GetModuleFileNameW(SELF_MODULE as HMODULE, buffer.as_mut_ptr(), buffer.len() as u32)
        } as usize;
        if n == 0 {
            return;
        }
        if n < buffer.len() {
            break n;
        }
        if buffer.len() >= 1 << 16 {
            return; // absurdly long path; give up rather than loop
        }
        buffer.resize(buffer.len() * 2, 0);
    };

    let self_path = std::path::PathBuf::from(std::ffi::OsString::from_wide(&buffer[..n]));
    let dir = match self_path.parent() {
        Some(d) => d.to_path_buf(),
        None => return,
    };

    let mut seen = std::collections::HashSet::new();
    load_asi_from(&dir, &mut seen);
    load_asi_from(&dir.join("plugins"), &mut seen);
}

unsafe extern "system" fn asi_thread(_param: *mut c_void) -> u32 {
    load_all_asi();
    0
}

/// Spawn the plugin sweep on its own thread. Used for the dynamic-load path,
/// and as a fallback if the entry-point trampoline can't be installed.
unsafe fn spawn_asi_thread() {
    let thread = CreateThread(
        core::ptr::null_mut(),
        0,
        asi_thread,
        core::ptr::null_mut(),
        0,
        core::ptr::null_mut(),
    );
    if !thread.is_null() {
        CloseHandle(thread);
    }
}

/// Restore the host entry point's original bytes. Idempotent.
unsafe fn restore_entry_bytes() {
    let p = REAL_ENTRY as *mut u8;
    if p.is_null() {
        return;
    }
    let mut old = 0u32;
    if VirtualProtect(p as *mut c_void, JMP_LEN, PAGE_EXECUTE_READWRITE, &mut old) == 0 {
        return;
    }
    core::ptr::copy_nonoverlapping(
        core::ptr::addr_of!(SAVED_ENTRY_BYTES) as *const u8,
        p,
        JMP_LEN,
    );
    let mut old2 = 0u32;
    VirtualProtect(p as *mut c_void, JMP_LEN, old, &mut old2);
    FlushInstructionCache(GetCurrentProcess(), p as *const c_void, JMP_LEN);
}

/// Called from the entry-point thunk on the host's own thread, after process
/// init, before host code runs. Restore the entry point, then sweep plugins.
unsafe extern "system" fn trampoline_load() {
    // Always restore first, so the thunk jumps back into clean host code.
    restore_entry_bytes();
    load_all_asi();
}

/// Naked trampoline planted at the host entry point. Entered via an absolute
/// jump with a pristine entry-point stack, it preserves the volatile registers
/// and flags, loads plugins, then jumps to the (now-restored) real entry with
/// state untouched — the host proceeds as if nothing happened.
#[unsafe(naked)]
unsafe extern "system" fn entry_thunk() {
    core::arch::naked_asm!(
        "push rax",
        "push rcx",
        "push rdx",
        "push r8",
        "push r9",
        "push r10",
        "push r11",
        "pushfq",
        "sub rsp, 0x28", // shadow space + 16-byte alignment for the call
        "call {load}",
        "add rsp, 0x28",
        "popfq",
        "pop r11",
        "pop r10",
        "pop r9",
        "pop r8",
        "pop rdx",
        "pop rcx",
        "pop rax",
        "jmp qword ptr [rip + {entry}]",
        load = sym trampoline_load,
        entry = sym REAL_ENTRY,
    )
}

/// Plant the trampoline over the host EXE's entry point. Returns false if the
/// PE looks wrong or the patch can't be written, so the caller can fall back.
unsafe fn install_entry_hook() -> bool {
    let base = GetModuleHandleW(core::ptr::null()) as *const u8;
    if base.is_null() {
        return false;
    }

    // IMAGE_DOS_HEADER.e_lfanew -> IMAGE_NT_HEADERS64.
    let e_lfanew = *(base.add(0x3C) as *const i32);
    if e_lfanew <= 0 {
        return false;
    }
    let nt = base.add(e_lfanew as usize);
    // "PE\0\0" signature, then PE32+ optional-header magic.
    if *(nt as *const u32) != 0x0000_4550 || *(nt.add(24) as *const u16) != 0x20B {
        return false;
    }
    // OptionalHeader (nt+24) . AddressOfEntryPoint (+16).
    let entry_rva = *(nt.add(24 + 16) as *const u32) as usize;
    if entry_rva == 0 {
        return false;
    }

    let real_entry = base.add(entry_rva) as *mut u8;
    REAL_ENTRY = real_entry as usize;
    core::ptr::copy_nonoverlapping(
        real_entry,
        core::ptr::addr_of_mut!(SAVED_ENTRY_BYTES) as *mut u8,
        JMP_LEN,
    );

    // FF 25 00 00 00 00 | <thunk address>  ==  jmp qword ptr [rip+0]; dq thunk
    let mut patch = [0u8; JMP_LEN];
    patch[0] = 0xFF;
    patch[1] = 0x25;
    patch[6..].copy_from_slice(&(entry_thunk as *const () as u64).to_le_bytes());

    let mut old = 0u32;
    if VirtualProtect(real_entry as *mut c_void, JMP_LEN, PAGE_EXECUTE_READWRITE, &mut old) == 0 {
        REAL_ENTRY = 0;
        return false;
    }
    core::ptr::copy_nonoverlapping(patch.as_ptr(), real_entry, JMP_LEN);
    let mut old2 = 0u32;
    VirtualProtect(real_entry as *mut c_void, JMP_LEN, old, &mut old2);
    FlushInstructionCache(GetCurrentProcess(), real_entry as *const c_void, JMP_LEN);
    true
}

#[no_mangle]
pub extern "system" fn DllMain(module: HMODULE, reason: u32, reserved: *mut c_void) -> i32 {
    if reason == DLL_PROCESS_ATTACH {
        unsafe {
            SELF_MODULE = module as usize;
            DisableThreadLibraryCalls(module);
            resolve_original();

            // `reserved != null` == static import: the host entry point hasn't run
            // yet, so trampoline it for a deterministic, race-free, main-thread load.
            // `reserved == null` == LoadLibrary: already past init, a thread is safe.
            if !reserved.is_null() {
                if !install_entry_hook() {
                    spawn_asi_thread();
                }
            } else {
                spawn_asi_thread();
            }
        }
    }
    1
}
